import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import "dotenv/config";

const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not defined in environment variables");
}

const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

export const SUPABASE_STAFF_MOCK = [
  {
    id: "staff-1",
    name: "Thanyawit Teengan (ธัญวิชญ์ ทีหงัน)",
    role: "ประธานมัคนายก",
    department: "Pastoral",
    deaconDepartment: "ประธาน",
    status: "online",
    phone: "084-504-8418",
    email: "thanyawit@maitrichit.org",
    lineId: "@thanyawit.t",
    avatarBg: "#EF5350",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Thanyawit+Teengan&background=EF5350&color=fff&size=128",
    joinedDate: "1 Jan 2010",
    birthday: "15 Mar 1972",
    bio: "ประธานมัคนายกและศิษยาภิบาลคริสตจักรไมตรีจิต 1837",
    address: "กรุงเทพมหานคร",
    skills: ["Preaching", "Pastoral Care", "Leadership", "Worship"],
  },
  {
    id: "staff-2",
    name: "มน.วชิรวรรณ รักษาสัตย์",
    role: "รองประธานมัคนายก",
    department: "Pastoral",
    deaconDepartment: "รองประธาน",
    status: "online",
    phone: "089-770-2379",
    email: "wachirawan@maitrichit.org",
    lineId: "@wachirawan.r",
    avatarBg: "#42A5F5",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Wachirawan+R&background=42A5F5&color=fff&size=128",
    joinedDate: "5 Mar 2015",
    birthday: "22 Jun 1985",
    bio: "รองประธานมัคนายก ดูแลการประสานงานและพิธีการนมัสการ",
    address: "นนทบุรี",
    skills: ["Worship Leading", "Pastoral Care", "Coordination"],
  },
  {
    id: "staff-3",
    name: "มน.บุญเลิศ ศรีสวัสดิ์",
    role: "มัคนายก",
    department: "Education",
    deaconDepartment: "คริสเตียนศึกษา",
    status: "meeting",
    phone: "082-111-2233",
    email: "boonlert@maitrichit.org",
    lineId: "@boonlert.s",
    avatarBg: "#66BB6A",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Boonlert+S&background=66BB6A&color=fff&size=128",
    joinedDate: "12 Jun 2016",
    birthday: "3 Nov 1980",
    bio: "มัคนายกฝ่ายคริสเตียนศึกษาและโรงเรียนวันอาทิตย์",
    address: "กรุงเทพมหานคร",
    skills: ["Teaching", "Curriculum", "Sunday School"],
  },
  {
    id: "staff-4",
    name: "มน.ชาญชัย วัฒนกุล",
    role: "มัคนายก",
    department: "Office",
    deaconDepartment: "งานอาคารสถานที่",
    status: "offline",
    phone: "086-555-4444",
    email: "chanchai@maitrichit.org",
    lineId: "@chanchai.w",
    avatarBg: "#FFA726",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Chanchai+W&background=FFA726&color=fff&size=128",
    joinedDate: "20 Sep 2017",
    birthday: "8 Aug 1978",
    bio: "มัคนายกฝ่ายอาคารสถานที่และการบำรุงรักษาพระนิเวศ",
    address: "ปทุมธานี",
    skills: ["Facility Management", "Maintenance", "Logistics"],
  },
  {
    id: "staff-5",
    name: "มน.ศิริพร เกียรติคุณ",
    role: "มัคนายก",
    department: "Pastoral",
    deaconDepartment: "งานสตรี",
    status: "online",
    phone: "081-999-8888",
    email: "siriporn@maitrichit.org",
    lineId: "@siriporn.k",
    avatarBg: "#EC407A",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Siriporn+K&background=EC407A&color=fff&size=128",
    joinedDate: "1 Jan 2018",
    birthday: "17 Apr 1982",
    bio: "มัคนายกฝ่ายสตรีและกลุ่มพันธกิจครอบครัว",
    address: "สมุทรปราการ",
    skills: ["Counseling", "Women Ministry", "Fellowship"],
  },
  {
    id: "staff-6",
    name: "มน.พงษ์เทพ สุนทรกุล",
    role: "มัคนายก",
    department: "Worship",
    deaconDepartment: "งานดนตรี",
    status: "online",
    phone: "083-444-5566",
    email: "pongthep@maitrichit.org",
    lineId: "@pongthep.m",
    avatarBg: "#AB47BC",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Pongthep+S&background=AB47BC&color=fff&size=128",
    joinedDate: "15 Aug 2018",
    birthday: "25 Sep 1991",
    bio: "มัคนายกฝ่ายดนตรีและการนมัสการ ควบคุมทีมขับร้องและเครื่องดนตรี",
    address: "กรุงเทพมหานคร",
    skills: ["Music Directing", "Worship Leading", "Sound Engineering"],
  },
  {
    id: "staff-7",
    name: "มน.จิตติมา มิตรไมตรี",
    role: "มัคนายก",
    department: "Office",
    deaconDepartment: "งานต้อนรับ",
    status: "online",
    phone: "085-667-8899",
    email: "jittima@maitrichit.org",
    lineId: "@jittima.m",
    avatarBg: "#26A69A",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Jittima+M&background=26A69A&color=fff&size=128",
    joinedDate: "10 Feb 2019",
    birthday: "12 Dec 1987",
    bio: "มัคนายกฝ่ายต้อนรับและปฏิคม ดูแลผู้มาเยือนและสมาชิกใหม่",
    address: "กรุงเทพมหานคร",
    skills: ["Ushering", "Hospitality", "Visitor Care"],
  },
  {
    id: "staff-8",
    name: "มน.วิชัย ชัยชนะ",
    role: "มัคนายก",
    department: "Office",
    deaconDepartment: "งานปฏิคม",
    status: "meeting",
    phone: "087-333-2211",
    email: "wichai@maitrichit.org",
    lineId: "@wichai.c",
    avatarBg: "#78909C",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Wichai+C&background=78909C&color=fff&size=128",
    joinedDate: "1 May 2019",
    birthday: "19 Oct 1983",
    bio: "มัคนายกฝ่ายปฏิคมและจัดเตรียมอาหารการรับรอง",
    address: "นนทบุรี",
    skills: ["Hospitality", "Food Logistics", "Event Coordination"],
  },
  {
    id: "staff-9",
    name: "มน.ปิยะพันธุ์ เยาวชนกุล",
    role: "มัคนายก",
    department: "Youth",
    deaconDepartment: "งานเยาวชน",
    status: "online",
    phone: "089-123-4567",
    email: "piyapan@maitrichit.org",
    lineId: "@piyapan.y",
    avatarBg: "#5C6BC0",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Piyapan+Y&background=5C6BC0&color=fff&size=128",
    joinedDate: "1 Sep 2020",
    birthday: "14 Jul 1993",
    bio: "มัคนายกฝ่ายเยาวชน พันธกิจนักเรียนนักศึกษาและคนรุ่นใหม่",
    address: "กรุงเทพมหานคร",
    skills: ["Youth Ministry", "Camp Planning", "Mentorship"],
  },
  {
    id: "staff-10",
    name: "มน.วรรณลักษณ์ ประชาสัมพันธ์",
    role: "มัคนายก",
    department: "Media",
    deaconDepartment: "งานประชาสัมพันธ์",
    status: "online",
    phone: "088-776-6554",
    email: "wannaluk@maitrichit.org",
    lineId: "@wannaluk.p",
    avatarBg: "#FF7043",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Wannaluk+P&background=FF7043&color=fff&size=128",
    joinedDate: "15 Jan 2021",
    birthday: "28 Feb 1990",
    bio: "มัคนายกฝ่ายประชาสัมพันธ์ สื่อสารองค์กรและสูจิบัตร",
    address: "กรุงเทพมหานคร",
    skills: ["Public Relations", "Graphic Design", "Social Media"],
  },
  {
    id: "staff-11",
    name: "มน.สาธินี พิธีการเลิศ",
    role: "มัคนายก",
    department: "Pastoral",
    deaconDepartment: "งานพิธีการ",
    status: "online",
    phone: "084-222-3311",
    email: "sathinee@maitrichit.org",
    lineId: "@sathinee.p",
    avatarBg: "#8D6E63",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Sathinee+P&background=8D6E63&color=fff&size=128",
    joinedDate: "10 Jun 2021",
    birthday: "5 May 1986",
    bio: "มัคนายกฝ่ายพิธีการ พิธีมหาสนิทและบัพติศมา",
    address: "กรุงเทพมหานคร",
    skills: ["Communion Setup", "Liturgical Order", "Baptism Care"],
  },
  {
    id: "staff-12",
    name: "มน.เฉลิมพร สงเคราะห์ชัย",
    role: "มัคนายก",
    department: "Relief",
    deaconDepartment: "งานสงเคราะห์",
    status: "offline",
    phone: "086-111-9988",
    email: "chalermporn@maitrichit.org",
    lineId: "@chalermporn.s",
    avatarBg: "#29B6F6",
    avatarColor: "#fff",
    avatarUrl: "https://ui-avatars.com/api/?name=Chalermporn+S&background=29B6F6&color=fff&size=128",
    joinedDate: "1 Nov 2021",
    birthday: "30 Jan 1975",
    bio: "มัคนายกฝ่ายสังคมสงเคราะห์ เยี่ยมเยียนผู้ป่วยและผู้สูงอายุ",
    address: "ปทุมธานี",
    skills: ["Social Relief", "Hospital Visitation", "Community Care"],
  },
];

async function main() {
  console.log("Start seeding 12 Mockup Staff & Deacons for Supabase...");
  for (const staff of SUPABASE_STAFF_MOCK) {
    const upserted = await prisma.staff.upsert({
      where: { email: staff.email },
      update: staff,
      create: staff,
    });
    console.log(`Upserted staff in Supabase: ${upserted.name} (${upserted.deaconDepartment})`);
  }
  console.log("Supabase Mockup Seeding finished successfully.");
}

main()
  .catch((e) => {
    console.error("Seed error:", e.message);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
